# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='lister',
            name='city',
            field=models.CharField(default='raleigh', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='lister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.Lister'),
        ),
        migrations.AddField(
            model_name='item',
            name='lister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.Lister'),
        ),
    ]
