# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0002_auto_20161127_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='lister',
            name='e_mail',
            field=models.CharField(default='example@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
