# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0003_lister_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lister',
            name='password',
            field=models.CharField(default='pass', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lister',
            name='username',
            field=models.CharField(default='username', max_length=20),
            preserve_default=False,
        ),
    ]
