# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0004_auto_20161127_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lister',
            name='password',
        ),
        migrations.RemoveField(
            model_name='lister',
            name='username',
        ),
    ]
